name: Status Check
on:
  push:
    branches:
      - '**'
      - '!master'

jobs:
  check1:
    name: Check 1
    runs-on: ubuntu-latest

    steps:
      - name: something test1
        run: exit 0

  check2:
    name: Check 2
    runs-on: ubuntu-latest

    steps:
      - name: something test2
        run: exit 0